// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr3oPf6qJcxQtWPp2InvKipI93UFydQRY',
    appId: '1:46356875969:web:346843d9d258768c8fa240',
    messagingSenderId: '46356875969',
    projectId: 'fir-app-cb036',
    authDomain: 'fir-app-cb036.firebaseapp.com',
    storageBucket: 'fir-app-cb036.firebasestorage.app',
    measurementId: 'G-J48C3EZ8LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWYdUiFXLsyuynrNeO_FrUCAgxacRHSF0',
    appId: '1:46356875969:android:1ce45431b2ce9fcc8fa240',
    messagingSenderId: '46356875969',
    projectId: 'fir-app-cb036',
    storageBucket: 'fir-app-cb036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoi03BfVpkz8ZUCpjeZ-GDsKhj07ET2ss',
    appId: '1:46356875969:ios:51c2ca0422faf99b8fa240',
    messagingSenderId: '46356875969',
    projectId: 'fir-app-cb036',
    storageBucket: 'fir-app-cb036.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoi03BfVpkz8ZUCpjeZ-GDsKhj07ET2ss',
    appId: '1:46356875969:ios:51c2ca0422faf99b8fa240',
    messagingSenderId: '46356875969',
    projectId: 'fir-app-cb036',
    storageBucket: 'fir-app-cb036.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr3oPf6qJcxQtWPp2InvKipI93UFydQRY',
    appId: '1:46356875969:web:9b36bceabbbdc80e8fa240',
    messagingSenderId: '46356875969',
    projectId: 'fir-app-cb036',
    authDomain: 'fir-app-cb036.firebaseapp.com',
    storageBucket: 'fir-app-cb036.firebasestorage.app',
    measurementId: 'G-TZZFQZW1K9',
  );
}
